" Remember to install Vundle first
" (https://github.com/VundleVim/Vundle.vim#quick-start), startup vim and type
" :PluginInstall to get the plugins installed.

syn on

set number
set noswapfile
set nowrap
set cursorline
set autoread
set incsearch
set backspace=2
set re=1
set scrolloff=10
set clipboard=unnamed
set colorcolumn=101
set laststatus=2
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set updatetime=250
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

" Vundle config start

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Plugins

Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'arcticicestudio/nord-vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'itchyny/lightline.vim'
Plugin 'xolox/vim-misc'
Plugin 'danro/rename.vim'
Plugin 'elixir-editors/vim-elixir'

" Vundle config end

call vundle#end()
filetype plugin indent on

" Syntastic config

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_loc_list_height=2
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_elixir_checkers = ['elixir']
let g:syntastic_enable_elixir_checker = 1
let g:syntastic_javascript_checkers=['eslint']
let g:syntastic_javascript_eslint_exe='$(npm bin)/eslint'

" CtrlP config

set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|deps\|_build'

" Nord config ('colorscheme nord' must be the last line)

let g:lightline = {
      \ 'colorscheme': 'nord',
      \ }
colorscheme nord

