" Remember to install Vundle first
" (https://github.com/VundleVim/Vundle.vim#quick-start), startup vim and type
" :PluginInstall to get the plugins installed.

syn on

set autochdir
set autoread
set backspace=2
set clipboard=unnamed
set colorcolumn=101
set cursorline
set incsearch
set laststatus=2
set nohlsearch
set noswapfile
set nowrap
set re=1
set relativenumber
set scrolloff=10
set splitbelow
set splitright
set statusline+=%#warningmsg#
set statusline+=%*
set statusline+=%{SyntasticStatuslineFlag()}
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
set term=xterm-256color
set termguicolors
set updatetime=250
set wildmenu

" Remaps
nnoremap ; :

" Vundle config start

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Plugins

Plugin 'airblade/vim-gitgutter'
Plugin 'arcticicestudio/nord-vim'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'cespare/vim-toml'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'itchyny/lightline.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'szymonmaszke/vimpyter'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-syntastic/syntastic'

" Vundle config end

call vundle#end()
filetype plugin indent on

" Syntastic config

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_loc_list_height=2
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_elixir_checker = 1

let g:syntastic_elixir_checkers = ['elixir']
let g:syntastic_javascript_checkers=['eslint']
let g:syntastic_javascript_eslint_exec = 'eslint_d'
let g:syntastic_json_checkers = ['jsonlint']
let g:syntastic_typescript_checkers = ['tslint', 'tsc']

" CtrlP config

set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|deps\|_build\|python*'

" wildmenu config
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.ico
set wildignore+=*.pdf,*.psd
set wildignore+=node_modules/*,bower_components/*

" Nord config ('colorscheme nord' must be the last line)

let g:lightline = {
      \ 'colorscheme': 'nord',
      \ }

colorscheme nord

" Better color for trailing spaces
hi ExtraWhitespace guibg=#BF616A
