" Remember to install Vundle first
" (https://github.com/VundleVim/Vundle.vim#quick-start), startup vim and type
" :PluginInstall to get the plugins installed.

syn off

set autochdir
set autoread
set backspace=2
set clipboard=unnamed
set colorcolumn=80,90,100
set cursorline
set ignorecase
set incsearch
set laststatus=2
set mouse=a
set nohlsearch
set noswapfile
set nowrap
set re=1
set relativenumber
set scrolloff=10
set smartcase
set splitbelow
set splitright
set statusline+=%#warningmsg#
set statusline+=%*
set statusline+=%{SyntasticStatuslineFlag()}
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
set tags=tags;~/Documents/workspace
set termguicolors
set updatetime=250
set wildmenu
set wrap

" Remaps
map ; :
map <C-c> <Esc>
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
map <S-h> gT
map <S-l> gt
nnoremap <C-p> :GFiles<Cr>
nnoremap <C-g> :Ag<Cr>

" Allow meta keys in terminal:
tmap <silent> <M-b> <C-w>:call term_sendkeys(bufnr('%'), "\<lt>Esc>b")<CR>
tmap <silent> <M-d> <C-w>:call term_sendkeys(bufnr('%'), "\<lt>Esc>d")<CR>
tmap <silent> <M-f> <C-w>:call term_sendkeys(bufnr('%'), "\<lt>Esc>f")<CR>
tmap <silent> <M-e> <C-w>:call term_sendkeys(bufnr('%'), "\<lt>Esc>e")<CR>

" :term buffer remaps
tmap <C-n> <C-w>N
tmap <C-h> <C-w>h
tmap <C-j> <C-w>j
tmap <C-k> <C-w>k
tmap <C-l> <C-w>l
tmap <C-w>H <C-w>gT
tmap <C-w>L <C-w>gt

" Vundle config start

set nocompatible

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'airblade/vim-gitgutter'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'cespare/vim-toml'
Plugin 'dense-analysis/ale'
Plugin 'itchyny/lightline.vim'
Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plugin 'junegunn/fzf.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'rust-lang/rust.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'

" Vundle config end

call vundle#end()
filetype plugin indent on

" ALE config
let g:ale_javascript_eslint_use_global = 1
let g:ale_javascript_eslint_executable = 'eslint_d'

let g:ale_linters = {
      \ 'javascript': ['eslint'],
      \ 'typescript': ['tslint'],
      \ }

let g:ale_fixers = {
      \ 'javascript': ['eslint'],
      \ 'typescript': ['tslint'],
      \ }

" CtrlP config

" set wildignore+=*/tmp/*,*.so,*.swp,*.zip
" set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe
" let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|deps\|python*'

" wildmenu config
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.ico
set wildignore+=*.pdf,*.psd
set wildignore+=node_modules/*,bower_components/*

if &term =~ '256color'
    " Disable Background Color Erase (BCE) so that color schemes
    " work properly when Vim is used inside tmux and GNU screen.
    set t_ut=
endif

" Papercolor config ('colorscheme PaperColor' must be the last line)

let g:lightline = {
      \ 'colorscheme': 'PaperColor',
      \ }

colorscheme PaperColor

" Cursor options
let &t_RS = "\<Esc>[6 q"
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[6 q"
let &t_EI = "\<Esc>[6 q"

set background=light

" Better color for trailing spaces
hi ExtraWhitespace guibg=#BF616A

" Windows options
if has("win32")
    set shell=C:\Windows\Sysnative\wsl.exe
    set shellpipe=|
    set shellredir=>
    set shellcmdflag=
endif

" Set GUI options
set guioptions=aegitk
set guicursor+=n-v-c:blinkon0
set guicursor+=i:blinkwait10

" Only on linux:
if has("gui_gtk2") || has("gui_gtk3")
    set guifont=Monospace\ 9
endif

" Only on macOS:
if has("gui_gtk2") || has("gui_gtk3")
    set guifont=Menlo-Regular:h13
endif
